### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by sinnlosername**

### CODE REVIEW

**Comment by sschwei1** [comment]
waiting for this to be accepted ....
this is a needed fix!!!

**Comment by sinnlosername** [comment]
yes you are right!!!

**Comment by sschwei1** [comment]
not sure how this typo was even made in the first place

**Comment by sinnlosername** [comment]
yes I don't think he was. probably some script kiddy who doesnt even understand the code

**Comment by sinnlosername** [comment]
what is this even for? some school project?

**Comment by sschwei1** [comment]
hopefully this is not used for any illegal purposes

**Comment by sinnlosername** [comment]
well never trust a guy with a default profile picture lmao

**Comment by sschwei1** [comment]
true

**Comment by sschwei1** [comment]
seems like this is getting ignored .. waiting for it

**Comment by sinnlosername** [comment]
same

**Comment by sschwei1** [comment]
@sinnlosername Ur opinion on closing this issue?

**Comment by sinnlosername** [comment]
@sschwei1 can probably do because lazy developer wont check anyways

**Comment by sschwei1** [comment]
@sinnlosername you know why this pr got closed?

**Comment by sschwei1** [comment]
@sinnlosername I think this PR should be reactivated

**Comment by sinnlosername** [comment]
i also think so but the developer still no response

**Pull request closed without merging**
